apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tran
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AralAskarov/golang.git
    targetRevision: main
    path: Chart-Arlan
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true