apiVersion: v1
kind: ConfigMap
metadata:
  name: db2-migrations
data:
  "V1__init.sql": |
    CREATE TABLE transactions (
        id SERIAL PRIMARY KEY,
        uuid BYTEA NOT NULL,
        amount INT NOT NULL,
        type TEXT NOT NULL CHECK (type IN ('deposit', 'withdrawal')),
        time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    
    COMMENT ON COLUMN transactions.uuid IS 'users.uuid';
    
    CREATE TABLE users (
        uuid TEXT,
        balance INT
    );