apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tran
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tran
    spec:
      containers:
      - name: tran-container
        image: {{ .Values.container.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_URL_MYSQL
            valueFrom:
              secretKeyRef:
                name: cred-mysql
                key: cred-mysql-connect
          - name: PORT
            value: "8080"
        securityContext:
          runAsUser: 0
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1500m
            memory: 1200Mi
      volumes:
      - name: migrations-volume
        configMap:
          name: db-migrations