apiVersion: v1
kind: ConfigMap
metadata:
  name: betting-service-config
data:
  GIN_MODE: "release"
  HTTP_PORT: "8080"
  DB_PATH: "/tmp/events.db"
  PAYOUT_SVC_URL: "http://golang.medhelper.xyz/dep/updateresults"
  PAYOUT_SVC_TIMEOUT: "5s"
  EVENT_SOURCE_URL: "https://arlan-api.azurewebsites.net" 
  EVENT_SOURCE_TIMEOUT: "15s"
  EVENT_SYNC_INTERVAL: "1m"
  CONFIG_PATH: "/tmp/config.yaml"