apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migrations
data:
  "init.sql": |
    DROP TABLE IF EXISTS sessions;
    DROP TABLE IF EXISTS users;
    DROP TABLE IF EXISTS transactions;

    CREATE TABLE users (
        uuid BINARY(16) PRIMARY KEY COMMENT 'UUID in binary format',
        email VARCHAR(255) UNIQUE NOT NULL,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        balance INT NOT NULL DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;

    CREATE INDEX idx_users_email ON users(email);

    CREATE TABLE sessions (
        token TEXT NOT NULL,
        user_uuid BINARY(16) NOT NULL,
        expires_at TIMESTAMP NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        user_agent VARCHAR(255) NOT NULL,
        ip_address VARCHAR(45) NOT NULL,
        INDEX idx_user_uuid (user_uuid),
        INDEX idx_expires_at (expires_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    CREATE TABLE transactions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        uuid BINARY(16) NOT NULL COMMENT 'users.uuid',
        amount INT NOT NULL,
        type ENUM('deposit', 'withdrawal') NOT NULL,
        time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO users (uuid, email, username, password, balance) 
    VALUES (UUID_TO_BIN(UUID(), 1), 'john@example.com', 'john_doe', '123', 1000);

    INSERT INTO users (uuid, email, username, password, balance) 
    VALUES (UUID_TO_BIN(UUID(), 1), 'alice@example.com', 'alice_smith', '123', 2500);

    INSERT INTO users (uuid, email, username, password, balance) 
    VALUES (UUID_TO_BIN(UUID(), 1), 'bob@example.com', 'bob_jones', '123', 500);
  
  "trigger.sql": |
    DELIMITER //
    CREATE TRIGGER before_users_insert 
    BEFORE INSERT ON users 
    FOR EACH ROW 
    BEGIN
        IF NEW.uuid IS NULL THEN
            SET NEW.uuid = UUID_TO_BIN(UUID(), 1);
        END IF;
    END//
    DELIMITER ;
