apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql  
spec:
  selector:
    matchLabels:
      app: mysql-sts  
  serviceName: mysql-service  
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-sts  
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - name: mysql-container  
        image: mysql:8.0
        args:
          - --log-bin-trust-function-creators=1
        volumeMounts:
        - name: mysql-pvc  
          mountPath: /var/lib/mysql  
        resources:
          requests:
            cpu: 1
            memory: 4Gi
        env:
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-credentials-root
              key: mysql-password
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_DATABASE  
          value: mydatabase
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: cred-mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc 
    spec:
      accessModes:
        - ReadWriteOnce
      # storageClassName: ebs-sc
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service  
spec:
  ports:
  - port: 3306  
  clusterIP: None
  selector:
    app: mysql-sts  